version: "3.8"

services:

  oracle:
    build:
      context: docker/oracle/.
      dockerfile: Dockerfile
    environment:
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    volumes:
#      - ./docker/oracle/.data:/opt/oracle/oradata
      - ./docker/oracle/docker-entrypoint-initdb.d:/opt/oracle/scripts/setup
      - ./docker/oracle/startup:/opt/oracle/scripts/startup
    ports:
      - ${ORACLE_PORT}:1521
      - ${ORACLE_MANAGE_PORT}:5500
    networks:
      - backend

  redis:
    build:
      context: docker/redis/.
      dockerfile: Dockerfile.dev
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend
    volumes:
      - ./docker/redis/.data:/data

networks:
  backend:
    driver: bridge

volumes:
  database:
    driver: local
