version: "3.8"

services:
  e-kadry:
    build:
      context: Docker/e-kadry/.
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app/
    ports:
      - ${E_KADRY_PORT}:${E_KADRY_PORT_ORIGIN}
    networks:
      - backend

  nginx:
    build:
      context: Docker/nginx/.
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH_HOST}/log:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - e-kadry
    networks:
      - frontend
      - backend

  oracle:
    build:
      context: Docker/oracle/.
      dockerfile: Dockerfile
    environment:
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    volumes:
      - ${DATA_PATH_HOST}/oracle/oradata:/opt/oracle/oradata
      - ${DATA_PATH_HOST}/oracle/scripts/setup:/opt/oracle/scripts/setup
      - ${DATA_PATH_HOST}/oracle/scripts/startup:/opt/oracle/scripts/startup
    ports:
      - ${ORACLE_PORT}:1521
      - ${ORACLE_MANAGE_PORT}:5500
    networks:
      - backend

  redis:
    build:
      context: Docker/redis/.
      dockerfile: Dockerfile.dev
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend
    volumes:
      - ${DATA_PATH_HOST}/redis:/data

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  database:
    driver: local
