version: "3.8"

services:
  api:
    build:
      context: docker/api/.
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/API:/app/
    ports:
      - ${API_PORT}:${API_PORT_ORIGIN}
    networks:
      - backend

  nginx:
    build:
      context: docker/nginx/.
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH_HOST}/log:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - api
    networks:
      - frontend
      - backend

  oracle:
    build:
      context: docker/oracle/.
      dockerfile: Dockerfile
    environment:
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_CHARACTERSET: ${ORACLE_CHARACTERSET}
    volumes:
      - ./docker/oracle/.data:/opt/oracle/oradata
      - ./docker/oracle/docker-entrypoint-initdb.d:/opt/oracle/scripts/setup
      - ./docker/oracle/startup:/opt/oracle/scripts/startup
    ports:
      - ${ORACLE_PORT}:1521
      - ${ORACLE_MANAGE_PORT}:5500
    networks:
      - backend

  redis:
    build:
      context: docker/redis/.
      dockerfile: Dockerfile.dev
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend
    volumes:
      - ./docker/redis/.data:/data

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  database:
    driver: local
